// <auto-generated />
using System;
using Elysium.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elysium.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220530195921_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryTour", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoutesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "RoutesId");

                    b.HasIndex("RoutesId");

                    b.ToTable("CategoryTour");
                });

            modelBuilder.Entity("Elysium.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Elysium.Model.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Elysium.Model.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Code = "rus",
                            Name = "Russian"
                        },
                        new
                        {
                            Code = "ara",
                            Name = "Arabic"
                        },
                        new
                        {
                            Code = "eng",
                            Name = "English"
                        },
                        new
                        {
                            Code = "fra",
                            Name = "French"
                        },
                        new
                        {
                            Code = "jpn",
                            Name = "Japanese"
                        },
                        new
                        {
                            Code = "deu",
                            Name = "German"
                        },
                        new
                        {
                            Code = "ita",
                            Name = "Italian"
                        },
                        new
                        {
                            Code = "spa",
                            Name = "Spanish"
                        });
                });

            modelBuilder.Entity("Elysium.Model.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("HouseNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.HasIndex("Longitude", "Latitude");

                    b.HasIndex("Name", "Region");

                    b.HasIndex("Region", "Name");

                    b.HasIndex("Country", "Region", "City", "Street", "HouseNumber");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Elysium.Model.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ScheduleItemId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Elysium.Model.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FBId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("InstagramId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("VKId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Rate");

                    b.ToTable("Proviers");
                });

            modelBuilder.Entity("Elysium.Model.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AvailableTicketNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndedAt")
                        .HasColumnType("date");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvailableTicketNumber");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TourId");

                    b.HasIndex("Price", "CurrencyId");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("Elysium.Model.RoutePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ScheduleItemId");

                    b.ToTable("RoutePoint");
                });

            modelBuilder.Entity("Elysium.Model.ScheduleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DayNumber");

                    b.HasIndex("TourId");

                    b.ToTable("ScheduleItems");
                });

            modelBuilder.Entity("Elysium.Model.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PhotoLink")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Elysium.Model.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ArchivedAt")
                        .HasColumnType("date");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("DirectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MainPhotoLink")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MainPhotoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MeetPointId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParticipateTerms")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Popularity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rate")
                        .HasColumnType("integer");

                    b.Property<string>("RouteDifficultyDescription")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TransferDetails")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("VisaDetails")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("VisaMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.HasIndex("DirectionId");

                    b.HasIndex("IsActive");

                    b.HasIndex("MeetPointId");

                    b.HasIndex("Name");

                    b.HasIndex("Popularity");

                    b.HasIndex("ProviderId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("LanguageTour", b =>
                {
                    b.Property<string>("LanguagesCode")
                        .HasColumnType("text");

                    b.Property<Guid>("ToursId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguagesCode", "ToursId");

                    b.HasIndex("ToursId");

                    b.ToTable("LanguageTour");
                });

            modelBuilder.Entity("TeamMemberTour", b =>
                {
                    b.Property<Guid>("TeamMembersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToursId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamMembersId", "ToursId");

                    b.HasIndex("ToursId");

                    b.ToTable("TeamMemberTour");
                });

            modelBuilder.Entity("CategoryTour", b =>
                {
                    b.HasOne("Elysium.Model.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elysium.Model.Tour", null)
                        .WithMany()
                        .HasForeignKey("RoutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elysium.Model.Photo", b =>
                {
                    b.HasOne("Elysium.Model.Location", null)
                        .WithMany("Photos")
                        .HasForeignKey("LocationId");

                    b.HasOne("Elysium.Model.ScheduleItem", "ScheduleItem")
                        .WithMany("Photos")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleItem");
                });

            modelBuilder.Entity("Elysium.Model.Ride", b =>
                {
                    b.HasOne("Elysium.Model.Currency", "Currency")
                        .WithMany("Tours")
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elysium.Model.Provider", null)
                        .WithMany("Tours")
                        .HasForeignKey("ProviderId");

                    b.HasOne("Elysium.Model.Tour", "Tour")
                        .WithMany("Rides")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Elysium.Model.RoutePoint", b =>
                {
                    b.HasOne("Elysium.Model.Location", "Location")
                        .WithMany("Points")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elysium.Model.ScheduleItem", "ScheduleItem")
                        .WithMany("RoutePoints")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ScheduleItem");
                });

            modelBuilder.Entity("Elysium.Model.ScheduleItem", b =>
                {
                    b.HasOne("Elysium.Model.Tour", "Tour")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Elysium.Model.Tour", b =>
                {
                    b.HasOne("Elysium.Model.Location", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elysium.Model.Location", "MeetPoint")
                        .WithMany()
                        .HasForeignKey("MeetPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elysium.Model.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("MeetPoint");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("LanguageTour", b =>
                {
                    b.HasOne("Elysium.Model.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elysium.Model.Tour", null)
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamMemberTour", b =>
                {
                    b.HasOne("Elysium.Model.TeamMember", null)
                        .WithMany()
                        .HasForeignKey("TeamMembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elysium.Model.Tour", null)
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elysium.Model.Currency", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Elysium.Model.Location", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("Elysium.Model.Provider", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Elysium.Model.ScheduleItem", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("RoutePoints");
                });

            modelBuilder.Entity("Elysium.Model.Tour", b =>
                {
                    b.Navigation("Rides");

                    b.Navigation("ScheduleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
